version: '3.1'

services:

  ghost:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    networks:
      - ghost

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    networks:
      - ghost
  
  nginx:
    image: nginx
    restart: always
    depends_on:
      - ghost
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$PWD/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - ghost

networks:
  ghost:
    driver: bridge
